modLoader="javafml"
loaderVersion="[47,)" # 对应 Forge 1.20.1 的版本范围
license="MIT"
issueTrackerURL="https://github.com/Yaaros/compete_with_oracle/issues"

[[mods]]
modId="compete_with_oracle" # 保持与文件夹一致，全小写下划线
version="1.0.0"
displayName="Compete With Oracle" # 游戏内显示的名称
displayURL="https://github.com/Yaaros/compete_with_oracle"
logoFile="logo.png" # 记得在 resources 根目录放一个 logo.png，否则删掉这行
credits="Yaaros"
authors="Yaaros"
description='''
一款多人“生存战争”模组。
包含随机传送、边界收缩、金钱与概念购买系统。
'''

[[dependencies.compete_with_oracle]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.compete_with_oracle]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

# 强依赖 Curios (饰品/被动效果)
[[dependencies.compete_with_oracle]]
modId="curios"
mandatory=true
versionRange="[5.14.1,)"
ordering="AFTER"
side="BOTH"